import Navigation from "@/components/Navigation";
import SectionUpp from "@/components/SectionUpp"
import Head from "next/head";

const Cuidados =  () => {
  return (
    <>
     <Head>
        <title>Ulceras Por Presión</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
    </Head> 
    <Navigation/>
    <SectionUpp/>
    </>
  )
}

export default Cuidados;
