import Layout from "@/components/layout/Layout";
import SectionUpp from "@/components/templates/SectionUpp";
import Head from "next/head";

const Cuidados = () => {
  return (
    <>
      <Head>
        <title>Ulceras Por Presión</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Layout>
       <SectionUpp />
      </Layout>
    </>
  );
};

export default Cuidados;
