import Navigation from '@/components/Navigation'
import Head from 'next/head'

const Productos = () => {
  return (
    <>
      <Head>
        <title>Ulceras Por Presión</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Navigation/>
    </>
  )
}

export default Productos
