import Layout from "@/components/layout/Layout";
import Section from "@/components/templates/Section";
import Head from "next/head";

export default function Productos () {
  return (
    <>
      <Head>
        <title>Ulceras Por Presión</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/react.png" />
      </Head>

      <Layout>
       <Section />
      </Layout>
    </>
  );
};
